"""Contract tests for the requirements report generated by the regrade pass."""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from aetherflow.core.verification_report import generate_results, write_results

PROJECT_ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def generated_report(tmp_path: Path) -> str:
    """Generate a fresh requirements report through the canonical code path."""
    results = generate_results(
        repo_root=PROJECT_ROOT,
        plan_path=PROJECT_ROOT / 'docs' / 'PLAN.md',
    )
    report_path = tmp_path / 'requirements-report.md'
    write_results(
        report_path=report_path,
        results_dir=tmp_path / 'verification-results',
        results=results,
    )
    return report_path.read_text(encoding='utf-8')


def test_requirements_report_has_all_six_states(generated_report: str):
    """docs/requirements-report.md must report all six state labels."""
    for state_label in (
        '- Retired:',
        '- Drafted:',
        '- Coded:',
        '- Evidenced:',
        '- Verified:',
        '- Complete:',
    ):
        assert state_label in generated_report, (
            f'Report missing state label: {state_label}'
        )


def test_each_item_entry_includes_required_fields(generated_report: str):
    """Each non-retired item section in the report must include key info."""
    # Each item section should have: ### AF-XX-XX header, Status:, Evidence Pack:
    item_sections = [
        f'### AF-{chunk}' for chunk in generated_report.split('\n### AF-')[1:]
    ]
    assert len(item_sections) >= 15, (
        f'Expected at least 15 item sections, found {len(item_sections)}'
    )
    for section in item_sections:
        if '- Status: retired' in section:
            continue
        assert '- Status:' in section, 'Missing status field in item section'
        assert '- Evidence Pack:' in section, (
            'Missing evidence-pack field in item section'
        )


def test_coded_items_not_shown_as_verified(generated_report: str):
    """Items that are coded or evidenced must not appear as verified in the report."""
    lines = generated_report.splitlines()
    # Find items that are 'coded' or 'evidenced' and verify they don't say 'verified'
    current_item = None
    for line in lines:
        if line.startswith('### AF-'):
            current_item = line
        if current_item and line.startswith('- Status:'):
            status = line.split(':', 1)[1].strip()
            if status in ('coded', 'evidenced'):
                # The status must not say 'verified'
                assert status != 'verified', (
                    f'{current_item} should not be verified but was: {status}'
                )


def test_retired_item_excluded_from_shipping_count(generated_report: str):
    """AF-00-01 is retired and must show status: retired, not be in verified count."""
    assert '- Retired: 1' in generated_report, (
        'Expected exactly 1 retired item (AF-00-01)'
    )
    # AF-00-01 section shows retired
    assert 'AF-00-01' in generated_report
    lines = generated_report.splitlines()
    in_af00_01 = False
    for line in lines:
        if '### AF-00-01' in line:
            in_af00_01 = True
        if in_af00_01 and line.startswith('- Status:'):
            assert 'retired' in line, f'AF-00-01 should be retired, got: {line}'
            break


def test_report_generated_from_evidence_states_not_heuristics(generated_report: str):
    """The report summary counts must be non-negative integers."""
    for label in ('Retired', 'Drafted', 'Coded', 'Evidenced', 'Verified', 'Complete'):
        match = re.search(rf'- {label}: (\d+)', generated_report)
        assert match is not None, f'Missing count for {label} in report'
        count = int(match.group(1))
        assert count >= 0
