# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import capture_pb2 as capture__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in capture_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CaptureControlStub(object):
    """Capture control-plane RPC surface. Timeout and retry posture is normative in
    docs/proto/capture.md and enforced by contract tests.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartCapture = channel.unary_unary(
                '/aetherflow.capture.v1.CaptureControl/StartCapture',
                request_serializer=capture__pb2.CaptureStartRequest.SerializeToString,
                response_deserializer=capture__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.StopCapture = channel.unary_unary(
                '/aetherflow.capture.v1.CaptureControl/StopCapture',
                request_serializer=capture__pb2.CaptureStopRequest.SerializeToString,
                response_deserializer=capture__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.ReportHeartbeat = channel.unary_unary(
                '/aetherflow.capture.v1.CaptureControl/ReportHeartbeat',
                request_serializer=capture__pb2.WorkerHeartbeat.SerializeToString,
                response_deserializer=capture__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.ForwardWorkerLog = channel.unary_unary(
                '/aetherflow.capture.v1.CaptureControl/ForwardWorkerLog',
                request_serializer=capture__pb2.WorkerLog.SerializeToString,
                response_deserializer=capture__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.ReportPluginLoadResult = channel.unary_unary(
                '/aetherflow.capture.v1.CaptureControl/ReportPluginLoadResult',
                request_serializer=capture__pb2.PluginLoadResult.SerializeToString,
                response_deserializer=capture__pb2.OperationStatus.FromString,
                _registered_method=True)
        self.ExportDiagnostics = channel.unary_unary(
                '/aetherflow.capture.v1.CaptureControl/ExportDiagnostics',
                request_serializer=capture__pb2.DiagnosticsExportRequest.SerializeToString,
                response_deserializer=capture__pb2.DiagnosticsExportResponse.FromString,
                _registered_method=True)


class CaptureControlServicer(object):
    """Capture control-plane RPC surface. Timeout and retry posture is normative in
    docs/proto/capture.md and enforced by contract tests.
    """

    def StartCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportHeartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardWorkerLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportPluginLoadResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportDiagnostics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaptureControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCapture,
                    request_deserializer=capture__pb2.CaptureStartRequest.FromString,
                    response_serializer=capture__pb2.OperationStatus.SerializeToString,
            ),
            'StopCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.StopCapture,
                    request_deserializer=capture__pb2.CaptureStopRequest.FromString,
                    response_serializer=capture__pb2.OperationStatus.SerializeToString,
            ),
            'ReportHeartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHeartbeat,
                    request_deserializer=capture__pb2.WorkerHeartbeat.FromString,
                    response_serializer=capture__pb2.OperationStatus.SerializeToString,
            ),
            'ForwardWorkerLog': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardWorkerLog,
                    request_deserializer=capture__pb2.WorkerLog.FromString,
                    response_serializer=capture__pb2.OperationStatus.SerializeToString,
            ),
            'ReportPluginLoadResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportPluginLoadResult,
                    request_deserializer=capture__pb2.PluginLoadResult.FromString,
                    response_serializer=capture__pb2.OperationStatus.SerializeToString,
            ),
            'ExportDiagnostics': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportDiagnostics,
                    request_deserializer=capture__pb2.DiagnosticsExportRequest.FromString,
                    response_serializer=capture__pb2.DiagnosticsExportResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aetherflow.capture.v1.CaptureControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aetherflow.capture.v1.CaptureControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CaptureControl(object):
    """Capture control-plane RPC surface. Timeout and retry posture is normative in
    docs/proto/capture.md and enforced by contract tests.
    """

    @staticmethod
    def StartCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherflow.capture.v1.CaptureControl/StartCapture',
            capture__pb2.CaptureStartRequest.SerializeToString,
            capture__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherflow.capture.v1.CaptureControl/StopCapture',
            capture__pb2.CaptureStopRequest.SerializeToString,
            capture__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportHeartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherflow.capture.v1.CaptureControl/ReportHeartbeat',
            capture__pb2.WorkerHeartbeat.SerializeToString,
            capture__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardWorkerLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherflow.capture.v1.CaptureControl/ForwardWorkerLog',
            capture__pb2.WorkerLog.SerializeToString,
            capture__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportPluginLoadResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherflow.capture.v1.CaptureControl/ReportPluginLoadResult',
            capture__pb2.PluginLoadResult.SerializeToString,
            capture__pb2.OperationStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportDiagnostics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aetherflow.capture.v1.CaptureControl/ExportDiagnostics',
            capture__pb2.DiagnosticsExportRequest.SerializeToString,
            capture__pb2.DiagnosticsExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
